name: React CI/CD Pipeline

# This triggers the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build and test the application
  build:
    runs-on: ubuntu-latest  # This specifies the OS for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up the Node.js environment
        with:
          node-version: '16'  # Specifies the version of Node.js

      - name: Install dependencies
        run: npm install  # Installs the required dependencies

      - name: Run tests
        run: npm test  # Runs your tests

      - name: Build the app
        run: npm run build  # Builds the React app for production

  # Job to deploy the application after build
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the deploy job runs only after the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Re-checks out the code for deployment

      - name: Deploy to Vercel
        run: vercel --prod  # Runs the Vercel deployment in production mode
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN }}  # Uses the Vercel token from GitHub Secrets